sudo: required
language: generic
services:
        - docker
        
before_install:
        - docker build -t amerychang/docker-react -f Dockerfile.dev .
        
script:
        - docker run -e CI=true amerychang/docker-react npm run test

